config:
    tls:
      enabled: true
      secretName: nats-cluster-tls
  jetstream:
    enabled: true
  merge:
    authorization:
      users:
      - user: platform-api-v3
      - user: platform-worker
      - user: platform-sms
      - user: platform-ums
      - user: platform-notsvc
      - user: platform-natsbox
      - user: platform-operator
  nats:
    tls:
      enabled: true
      merge:
        verify_and_map: true
      secretName: nats-server-tls
tlsCA:
  enabled: true
  secretName: platform-vault-ca 
