apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-nats 
  namespace: argocd
spec:
  project: howso-platform 
  source:
    repoURL: registry.how.so/howso-platform/dev-1 
    targetRevision: 1.1.5 
    chart: nats 
    helm:
      values: |
        config:
          jetstream:
            enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true