apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-postgres 
  namespace: argocd
spec:
  project: howso-platform 
  source:
    repoURL: registry.replicated.com/howso-platform/dev-1 
    targetRevision: 13.2.24 
    chart: postgresql 
    helm:
      values: |
        {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true