apiVersion: k3d.io/v1alpha3
kind: Simple
name: platformk8s 
servers: 1
agents: 0 
image: rancher/k3s:v1.27.9-k3s1 
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443 
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry-localhost 
    host: 0.0.0.0
    hostPort: "5000" 