consoleIngress:
  annotations:
    projectcontour.io/upstream-protocol.tls: '9000'
existingSecret: platform-minio
mode: standalone
tls:
  certSecret: platform-minio-server-tls
  enabled: true
  privateKey: tls.key
  publicCrt: tls.crt
trustedCertsSecret: platform-vault-ca
