apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: howso-platform 
  namespace: argocd
spec:
  project: howso-platform 
  source:
    repoURL: registry.how.so
    targetRevision: '*' 
    chart: howso-platform/stable/howso-platform 
    helm:
      values: |
        customResourceDefinitions:
          skip: true
        domain: local.howso.com
        images:
          registry: proxy.replicated.com
          registryNamespace: proxy/howso-platform/dpbuild-docker-edge.jfrog.io/dp
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true