apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: howso-platform 
  namespace: argocd
spec:
  project: howso-platform 
  source:
    repoURL: registry.how.so/howso-platform/stable
    targetRevision: 2.14.78
    chart: howso-platform 
    helm:
      values: |
        customResourceDefinitions:
          skip: true
        domain: local.howso.com
        images:
          registry: proxy.replicated.com
          registryNamespace: proxy/howso-platform/dpbuild-docker-edge.jfrog.io/dp
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-minio 
  namespace: argocd
spec:
  project: howso-platform
  source:
    repoURL: registry.how.so/howso-platform/stable
    targetRevision: 5.0.14 
    chart: minio 
    helm:
      values: |
        existingSecret: platform-minio
        mode: standalone
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-nats 
  namespace: argocd
spec:
  project: howso-platform 
  source:
    repoURL: registry.how.so/howso-platform/stable 
    targetRevision: 1.1.5 
    chart: nats 
    helm:
      values: |
        config:
          jetstream:
            enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-postgres 
  namespace: argocd
spec:
  project: howso-platform 
  source:
    repoURL: registry.how.so/howso-platform/stable 
    targetRevision: 13.2.24 
    chart: postgresql 
    helm:
      values: |
        auth:
          existingSecret: platform-postgres-postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-redis 
  namespace: argocd
spec:
  project: howso-platform 
  source:
    repoURL: registry.how.so/howso-platform/stable 
    targetRevision: 18.4.0 
    chart: redis 
    helm:
      values: |
        auth:
          existingSecret: platform-redis
        replica:
          replicaCount: 0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
