apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-minio
  namespace: argocd
spec:
  project: howso-platform
  source:
    repoURL: registry-1.docker.io
    targetRevision: '*'
    chart: bitnamicharts/minio
    helm:
      values: |
        console:
          enabled: false
        auth:
          existingSecret: platform-minio
          rootUserSecretKey: rootUser
          rootPasswordSecretKey: rootPassword
        defaultBuckets: platform
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-nats
  namespace: argocd
spec:
  project: howso-platform
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: '*'
    chart: nats
    helm:
      values: |
        config:
          jetstream:
            enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-postgres
  namespace: argocd
spec:
  project: howso-platform
  source:
    repoURL: registry-1.docker.io
    targetRevision: '*'
    chart: bitnamicharts/postgresql
    helm:
      values: |
        auth:
          existingSecret: platform-postgres-postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-redis
  namespace: argocd
spec:
  project: howso-platform
  source:
    repoURL: registry-1.docker.io
    targetRevision: '*'
    chart: bitnamicharts/redis
    helm:
      values: |
        auth:
          existingSecret: platform-redis
        commonConfiguration: |
          appendonly yes
          save ""
          notify-keyspace-events Kgh
        replica:
          replicaCount: 0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: howso
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
