apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-minio 
  namespace: argocd
spec:
  project: howso-platform
  source:
    repoURL: registry.replicated.com/howso-platform/dev-1
    targetRevision: 5.0.14 
    chart: minio 
    helm:
      values: |
        mode: standalone
        resources:
          requests:
            memory: 2Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true