apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: howso-platform
  namespace: argocd
spec:
  description: Howso Platform Applications
  sourceRepos:
    - 'registry.replicated.com/howso-platform/dev-1'
  destinations:
    - namespace: howso
      server: 'https://kubernetes.default.svc'