apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-redis-client-tls
spec:
  secretName: platform-redis-client-tls 
  commonName: platform-redis-client
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - Howso Platform
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - client auth
  dnsNames:
  - platform-redis-clients
  issuerRef:
    name: vault-issuer-internal-k8s
    kind: Issuer
