global:
  postgresql:
    auth:
      existingSecret: platform-postgres-postgresql
tls:
  certCAFilename: ca.crt
  certFilename: tls.crt
  certKeyFilename: tls.key
  certificatesSecret: platform-postgres-server-tls
  enabled: true