apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: api-v3-backend-transport
  namespace: howso
spec:
  rootCAsSecrets:
    - platform-app-tls-ca 
  serverName: platform-api-v3.default.svc.cluster.local
  insecureSkipVerify: false

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: platform-api-v3
  namespace: howso
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.local.howso.com`) && PathPrefix(`/api/v3/`)
      kind: Rule
      services:
        - name: platform-api-v3
          port: 8443
          serversTransport: api-v3-backend-transport
    - match: Host(`api.local.howso.com`) && Path(`/openapi.json`)
      kind: Rule
      services:
        - name: platform-api-v3
          port: 8443
          serversTransport: api-v3-backend-transport
  tls:
    secretName: platform-ingress-tls
