configPathmc: /tmp/
existingSecret: platform-minio
makeServiceAccountJob:
  securityContext:
    enabled: true
    runAsUser: null
mode: standalone
resources:
  requests:
    memory: 2Gi
securityContext:
  enabled: false
