master:
  containerSecurityContext:
    runAsUser: null
  podSecurityContext:
    fsGroup: null
metrics:
  containerSecurityContext:
    runAsUser: null
replica:
  containerSecurityContext:
    runAsUser: null
  podSecurityContext:
    fsGroup: null
sentinel:
  containerSecurityContext:
    runAsUser: null
