auth:
  existingSecret: platform-redis
commonConfiguration: '# Enable AOF https://redis.io/topics/persistence#append-only-file

  appendonly yes

  # Disable RDB persistence, AOF persistence already enabled.

  save ""

  # Enable keyspace events

  notify-keyspace-events Kgh'
master:
  containerSecurityContext:
    runAsUser: null
  podSecurityContext:
    fsGroup: null
metrics:
  containerSecurityContext:
    runAsUser: null
replica:
  containerSecurityContext:
    runAsUser: null
  podSecurityContext:
    fsGroup: null
  replicaCount: 0
sentinel:
  containerSecurityContext:
    runAsUser: null
