config:
  issuer: https://dex.local.howso.com
  storage:
    type: kubernetes
    config:
      inCluster: true
  web:
    http: 0.0.0.0:5556
  staticClients:
  - id: howso-platform
    redirectURIs:
    - 'https://management.local.howso.com/oidc/callback/'
    name: 'Howso Platform'
    secret: your-client-secret-here
  oauth2:
    responseTypes: ["code", "token", "id_token"]
    skipApprovalScreen: true
  enablePasswordDB: true
  staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"  # the hash of "password"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

ingress:
  enabled: true
  className: "traefik"
  annotations: 
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: dex.local.howso.com
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: dex-tls
      hosts:
        - dex.local.howso.com