oidc:
  enabled: true
  clientID: "howso-platform"
  clientSecret: "your-client-secret-here"
  algorithm: "RS256"
  jwksEndpoint: "http://dex.dex.svc.cluster.local:5556/keys"
  authorizeEndpoint: "http://dex.dex.svc.cluster.local:5556/auth"
  tokenEndpoint: "http://dex.dex.svc.cluster.local:5556/token"
  userinfoEndpoint: "http://dex.dex.svc.cluster.local:5556/userinfo"
  scopes: "openid email profile"