auth:
  existingSecret: platform-minio
  rootUserSecretKey: rootUser
  rootPasswordSecretKey: rootPassword
defaultBuckets: platform
image:
  registry: registry-localhost:5000
  repository: bitnami/minio
resources:
  requests:
    memory: 2Gi
