auth:
  existingSecret: platform-redis
commonConfiguration: |
  # Enable AOF https://redis.io/topics/persistence#append-only-file

  appendonly yes

  # Disable RDB persistence, AOF persistence already enabled.

  save ""

  # Enable keyspace events

  notify-keyspace-events Kgh
global:
  imageRegistry: registry-localhost:5000
image:
  repository: redis
replica:
  replicaCount: 0
